llm:
  provider: anthropic
  model: claude-3-haiku-20240307
  temperature: 0.1
  max_tokens: 1000

vector_db:
  provider: chromadb
  collection_name: watchdog_logs

application:
  log_level: INFO
  max_log_entries: 1000
  analysis_chunk_size: 5